---

- name: Basic playbook test
  gather_facts: true
  hosts: hosts
  tasks:
    - name: lanzando un ping
      ping:

    - name: Show info
      debug:
        msg: "Machine name: {{ ansible_hostname }}"
