---
- hosts: "all"
  become: true

- name: Copy a test file
  hosts: "all"
  tasks:
  - name: copy a test file
    copy:
      src_path: /var/lib/awx/projects/_16__sudo/files/tmp/hola.txt
      des_path: /tmp/
      owner: root
      group: root
      mode: '0644'

