---
- hosts: "all"
  become: true

- name: Copy a test file
  hosts: "all"
  tasks:
  - name: copy a test file
    copy:
      copy: src=sudoers.j2 dest=/tmp/sudoers
      owner: root
      group: root
      mode: '0644'

